### ISSUE TITLE
Add GQT template optimizer

### ISSUE THREAD

**Issue by romshark** [graph-guard/gqt#16]
Add a function for the optimization of GQT expressions.

Example:

```yml
location: 0:1:1-19:1:20
operationType: Query
selectionSet:
  location: 6:1:7-19:1:20
  selections:
  - location: 8:1:9-17:1:18
    selectionType: field
    name:
      location: 8:1:9-9:1:10
      name: f
    type: Int!
    argumentList:
      location: 9:1:10-17:1:18
      arguments:
      - location: 10:1:11-16:1:17
        name:
          location: 10:1:11-11:1:12
          name: a
        type: Int!
        constraint:
          location: 13:1:14-16:1:17
          constraintType: equals
          value:
            location: 13:1:14-16:1:17
            expressionType: addition
            float: false
            addendLeft:
              location: 13:1:14-14:1:15
              expressionType: int
              value: 1
            addendRight:
              location: 15:1:16-16:1:17
              expressionType: int
              value: 2
```

The AST above can be reduced to the following AST by eliminating the addition expression containing two constants:

```yml
location: 0:1:1-19:1:20
operationType: Query
selectionSet:
  location: 6:1:7-19:1:20
  selections:
  - location: 8:1:9-17:1:18
    selectionType: field
    name:
      location: 8:1:9-9:1:10
      name: f
    type: Int!
    argumentList:
      location: 9:1:10-17:1:18
      arguments:
      - location: 10:1:11-16:1:17
        name:
          location: 10:1:11-11:1:12
          name: a
        type: Int!
        constraint:
          location: 13:1:14-16:1:17
          expressionType: int
          value: 3
```
